### PR TITLE
Fixed S11.6.1_A2.2_T2

### PR DESCRIPTION
**Pull request by otac0n**
Fixed S11.6.1_A2.2_T2 by overriding DefaultValue on DateObject to treat a DevaultvalueHint of None as a DefaultValueHint of String.

This is as per the spec, section 11.6.1 (NOTE1):

> ... Date objects handle the absence of a hint as if the hint String were given. Host objects may handle the absence of a hint in some other manner.

### CODE REVIEW

**Comment by fholm** [comment]
Hey, awesome work! There's a "problem" with the sputnik tests though, the current version of IronJS uses a separate test runner application for sputnik that was custom built to ease debugging/development compared to the really slow visual studio test runner and I would prefer keeping it like that. 

It feels a bit unnecessary to add ~56k lines of code to be able to run the tests from within Visual Studio. I Like the DateObject fix though, I will try to pull that into master right away, same with the .gitignore fix.

**Comment by fholm** [comment]
Pulled the DateObject fix into the master branch and pushed back to github.

**Comment by otac0n** [comment]
@fholm Yeah, I meant to branch both of those changes from the same point on your master, but I accedentially made them linear.  I'm a little new to Git, what is it that I need to do, here?

**Comment by otac0n** [comment]
Ok, I've deleted my branch, since I see that this has been brought in to your master.

**Pull request closed without merging**
